# ==============================================================================
# Master Configuration for End-to-End YOLO Pipeline
#
# This file is the master control panel for the project, reorganized by function
# to centralize related settings. Scripts refer to this file at runtime.
# ==============================================================================


# ==============================================================================
# SECTION 1: DATASET & FILE PATHS
# All paths related to datasets, workspaces, and other file locations.
# ==============================================================================
dataset_paths:
  # [Script: 1a] The absolute path to the ros2bag folder that needs to be extracted.
  # This is the primary source of all image data for the entire pipeline.
  # USER ACTION REQUIRED: This path must be updated to your local environment.
  ros2bag_directory: '/home/your_name/your_ros2bag_directory'

  # [Script: 1a] Default directory where raw images will be saved after extraction from the ros2bag.
  extracted_images_dir: 'datasets/your_dataset'

  # [Scripts: 1b, 1c, 1d, 1e] Path to the initial, manually labeled dataset. This small, high-quality dataset
  # is used to train the very first Teacher model.
  initial_labeled_dataset: 'datasets/your_dataset'

  # [Scripts: 2a, active_learning_sampler] Path to the large pool of unlabeled images for the semi-supervised cycle.
  # The teacher model will generate pseudo-labels for this data.
  unlabeled_pool_dir: 'datasets/your_dataset'

  # [Scripts: 2b, 1b, 1c] Path to an auto-labeled dataset that requires human review. This dataset is processed
  # by the cleaner to remove noise or sent to the manual labeler for corrections.
  reviewed_dataset: 'datasets/your_dataset'
  
  # [Scripts: 2c, tools/merge] Path to the final, merged dataset created by combining the original
  # labeled data with the newly reviewed data. Used for retraining the Teacher model.
  merged_dataset_for_retrain: 'datasets/your_dataset'

  # [Script: 3a] Path to the large-scale, high-quality dataset completed in Phase 2,
  # which will be used for training the final lightweight Student model.
  final_training_dataset: 'datasets/your_dataset'

  # [Script: active_learning] Workspace directory for the Active Learning script.
  # Intermediate files like predictions and feature vectors will be stored here.
  active_learning_workspace: 'active_learning_workspace'

  # [Script: tools/merge] Default list of input dataset directories for the merge_datasets.py script.
  merge_tool_inputs:
    - 'datasets/your_dataset1'
    - 'datasets/your_dataset2'

  # [Script: tools/sample] Default source dataset for the random_sample_dataset.py script.
  sampling_tool_source: 'datasets/your_dataset'

  # [Script: tools/sample] Default output directory for the sampled dataset created by random_sample_dataset.py.
  sampling_tool_output: 'datasets/your_dataset'


# ==============================================================================
# SECTION 2: MODEL CONFIGURATIONS
# All settings related to model architecture, weights, and classes.
# ==============================================================================
model_configurations:
  # [Scripts: 1b, 1c, 1d, 2b] Defines the object classes for the model.
  # The key is the class ID (integer) and the value is the class name (string). This must be consistent across all phases.
  # Adjust the class names and IDs according to your project.
  classes:
    0: 'center_line'
    1: 'obstacle_vehicle'
    2: 'race_traffic_light'
    3: 'checkerboard'

  # [Scripts: 1e, 2a, 2c] Configuration for the Teacher model, which is used to generate pseudo-labels.
  teacher_model_config:
    # [Scripts: 1e, 2c, 2a] The name of the YOLO model architecture to use (e.g., 'yolov8n', 'yolov10m').
    model_name: 'yolov10m'
    # [Scripts: 1e, 2c, 3a] Hyperparameters for training the Teacher model.
    hyperparameters:
      # [Scripts: 1e, 2c, 3a] The total number of epochs for training.
      epochs: 1000
      # [Scripts: 1e, 2c, 3a] Number of epochs with no improvement after which training will be stopped.
      patience: 100
      # [Scripts: 1e, 2c, 3a] Model-specific parameters. The script will use 'default' if the specified
      # model_name is not found in this list.
      # Adjust the batch_sizes and img_size according to your gpu memory.
      models:
        yolov8x:
          batch_size: 8
          img_size: 608
        yolov10n:
          batch_size: 32
          img_size: 640
        yolov10s:
          batch_size: 16
          img_size: 640
        yolov10m:
          batch_size: 8
          img_size: 640
        default:
          batch_size: 16
          img_size: 640

  # [Script: 3a] Configuration for the final Student model, which is optimized for deployment.
  student_model_config:
    # [Script: 3a] The name of the YOLO architecture for the Student model.
    # This can be a lighter model than the Teacher for faster inference.
    model_name: 'yolov10n'
    # YOLO's "auto" mode automatically selects the hyperparameters.
  
  # [Script: 2a] Path to the trained Teacher model weights (.pt file) used for auto-labeling in the semi-supervised cycle.
  semi_supervised_weights: 'runs/train/yolov10m_result/weights/best.pt'
  
  # [Script: active_learning] Path to the trained model weights (.pt file) used for Active Learning predictions.
  active_learning_weights: 'runs/train/yolov10m_result/weights/best.pt'


# ==============================================================================
# SECTION 3: WORKFLOW & TOOL PARAMETERS
# Other parameters that control the behavior of the pipeline scripts.
# ==============================================================================
workflow_parameters:
  # [Scripts: 1a, 1b, 1d, 2a, 2b, tools/*] Global setting for image formats used across the project.
  # Comma-separated list of extensions without the dot.
  image_format: 'png,jpg,jpeg'

  # [Script: 1a] The ROS topic from which to extract images from the ros2bag file.
  ros2_image_topic: '/image_raw'

  # [Script: 1d] The ratio of the dataset to be used for the training set during the split.
  # The rest will be used for the validation set (e.g., 0.8 means 80% train, 20% val).
  train_split_ratio: 0.8

  # [Script: 2a] The confidence score threshold for auto-labeling.
  # Predictions with a confidence score below this value will be discarded.
  auto_label_confidence_threshold: 0.3

  # [Script: active_learning_sampler] The final number of images to select during the Active Learning process.
  active_learning_selection_size: 100

  # [Script: active_learning_sampler] The minimum average confidence for an image to be considered 'uncertain'.
  active_learning_min_confidence: 0.4

  # [Script: active_learning_sampler] The maximum average confidence for an image to be considered 'uncertain'.
  active_learning_max_confidence: 0.8

  # [Script: tools/random_sample_dataset] The default ratio of the dataset to sample when using random_sample_dataset.py.
  # (e.g., 0.1 means 10% of the dataset will be sampled).
  sampling_tool_ratio: 0.1