# ==============================================================================
# Master Configuration for End-to-End YOLO Pipeline
#
# This file contains settings related to model architecture and training hyperparameters.
# All file paths are now provided at runtime.
# ==============================================================================


# ==============================================================================
# SECTION 1: MODEL CONFIGURATIONS
# All settings related to model architecture, weights, and classes.
# ==============================================================================
model_configurations:
  # Defines the object classes for the model.
  # The key is the class ID (integer) and the value is the class name (string).
  # This must be consistent across all phases.
  classes:
    0: 'center_line'
    1: 'obstacle_vehicle'
    2: 'race_traffic_light'
    3: 'checkerboard'

  # Configuration for the Teacher model, which is used to generate pseudo-labels.
  teacher_model_config:
    # The name of the YOLO model architecture to use (e.g., 'yolov8n', 'yolov10m').
    model_name: 'yolov10m'
    # Hyperparameters for training the Teacher model.
    hyperparameters:
      epochs: 1000
      patience: 100
      # Model-specific parameters. The script will use 'default' if the specified
      # model_name is not found in this list.
      models:
        yolov8x:
          batch_size: 8
          img_size: 608
        yolov10n:
          batch_size: 32
          img_size: 640
        yolov10s:
          batch_size: 16
          img_size: 640
        yolov10m:
          batch_size: 8
          img_size: 640
        default:
          batch_size: 16
          img_size: 640

  # Configuration for the final Student model, which is optimized for deployment.
  student_model_config:
    # The name of the YOLO architecture for the Student model.
    model_name: 'yolov10n'
    # YOLO's "auto" mode automatically selects the hyperparameters.
  

# ==============================================================================
# SECTION 2: WORKFLOW & TOOL PARAMETERS
# Other parameters that control the behavior of the pipeline scripts.
# ==============================================================================
workflow_parameters:
  # Global setting for image formats used across the project.
  image_format: 'png,jpg,jpeg'

  # The ROS topic from which to extract images from the ros2bag file.
  ros2_image_topic: '/image_raw'

  # The ratio of the dataset to be used for the training set during the split.
  train_split_ratio: 0.8

  # The confidence score threshold for auto-labeling.
  auto_label_confidence_threshold: 0.3

  # The final number of images to select during the Active Learning process.
  active_learning_selection_size: 100

  # The minimum average confidence for an image to be considered 'uncertain'.
  active_learning_min_confidence: 0.4

  # The maximum average confidence for an image to be considered 'uncertain'.
  active_learning_max_confidence: 0.8

  # The default ratio of the dataset to sample when using random_sample_dataset.py.
  sampling_tool_ratio: 0.1
